<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>holomat_ros</name>
  <version>1.0.0</version>

  <description>Holomat</description>
  <maintainer email="santosmatthewjohn@gmail.com">MJ Santos</maintainer>

  <license>BSD-3-Clause</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>holomat_interface</exec_depend>
  <exec_depend>message_runtime</exec_depend>

  <!-- hand tracking dependencies -->
  <exec_depend>opencv-python</exec_depend>
  <exec_depend>mediapipe</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <!-- 
  pygame, openai, RealtimeSTT are Python packages that must be installed
  separately. They are not ROS packages, so they are not
  listed as <exec_depend> here. 
  -->

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
